### ISSUE TITLE
Issue In Controller.dart

### ISSUE THREAD

**Issue by Dinoy-Raj** [theindianappguy/flutter_google_sheets#3]
Launching lib\main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...
lib/controller.dart:19:26: Error: The argument type 'String' can't be assigned to the parameter type 'Uri'.
 - 'Uri' is from 'dart:core'.
      await http.get(URL + feedbackForm.toParams()).then(
                         ^
Failed to compile application.

**Comment by Aziz-cs** [comment]
Try to make http.get(Uri.parse(URL + feedbackForm.toParams())).then()
